# Generated by Django 5.2.6 on 2025-09-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название конкурса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('level', models.CharField(choices=[('center', 'Центровский'), ('city', 'Городской'), ('district', 'Районный'), ('republic', 'Республиканский'), ('regional', 'Региональный'), ('interregional', 'Межрегиональный'), ('allrussian', 'Всероссийский'), ('international', 'Международный')], max_length=20, verbose_name='Уровень')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Срок подачи заявок')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='Дата объявления результатов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип результата',
                'verbose_name_plural': 'Типы результатов',
                'ordering': ['name'],
            },
        ),
    ]
