# Generated by Django 5.2.6 on 2025-09-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_offline',
            field=models.BooleanField(default=True, verbose_name='Очное'),
        ),
    ]
