# Generated by Django 5.2.6 on 2025-09-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_offline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_offline',
            field=models.BooleanField(default=False, verbose_name='Очное'),
        ),
    ]
