# Generated by Django 5.2.6 on 2026-04-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_is_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На утверждении'), ('published', 'Опубликован')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
