# Generated by Django 5.2.6 on 2026-04-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название направления')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Направление конкурса',
                'verbose_name_plural': 'Направления конкурсов',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
