# Generated by Django 5.2.6 on 2026-04-14 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_competitiondirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.competitiondirection', verbose_name='Направление конкурса'),
        ),
    ]
