# Generated by Django 5.2.6 on 2026-04-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participation_format',
            field=models.CharField(choices=[('offline', 'Очная'), ('mixed', 'Очно-дистанционная'), ('online', 'Заочная')], default='offline', max_length=20, verbose_name='Формат участия'),
        ),
    ]
