# Generated by Django 5.2.6 on 2026-04-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_participation_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participation_format',
            field=models.CharField(blank=True, choices=[('offline', 'Очная'), ('mixed', 'Очно-дистанционная'), ('online', 'Заочная')], max_length=20, null=True, verbose_name='Формат участия'),
        ),
    ]
