# Generated by Django 5.2.6 on 2025-09-06 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_result', models.CharField(blank=True, max_length=255, verbose_name='Результат (произвольный)')),
                ('report_date', models.DateField(verbose_name='Дата отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child', verbose_name='Ребенок')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.studioenrollment', verbose_name='Запись в студию')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Конкурс')),
                ('result_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.resulttype', verbose_name='Тип результата')),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Участия',
                'ordering': ['-report_date', 'child__fio'],
                'unique_together': {('child', 'event')},
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('stored_name', models.CharField(max_length=255, verbose_name='Имя файла в системе')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байт)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME-тип')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participation.participation', verbose_name='Участие')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
                'ordering': ['-upload_date'],
            },
        ),
    ]
