# Generated by Django 5.2.6 on 2025-10-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_teacherstudioaccess'),
        ('events', '0004_alter_event_is_offline'),
        ('participation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('enrollment', 'event')},
        ),
    ]
