# Generated by Django 5.2.6 on 2026-01-27 03:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_teacherstudioaccess'),
        ('events', '0004_alter_event_is_offline'),
        ('participation', '0002_alter_participation_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('enrollment', 'event', 'created_by')},
        ),
    ]
