# Generated by Django 5.2.6 on 2026-04-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0003_alter_participation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
    ]
