# Generated by Django 5.2.6 on 2025-09-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['direction', 'name'], 'verbose_name': 'Студия', 'verbose_name_plural': 'Студии'},
        ),
        migrations.AddField(
            model_name='studio',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studios_in_direction', to='children.direction', verbose_name='Направление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название студии'),
        ),
        migrations.AlterUniqueTogether(
            name='studio',
            unique_together={('name', 'direction')},
        ),
    ]
