# Generated by Django 5.2.6 on 2025-09-06 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_alter_studio_options_studio_direction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudioAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предоставления доступа')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем предоставлен доступ')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.studio', verbose_name='Студия')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.teacher', verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Доступ педагога к студии',
                'verbose_name_plural': 'Доступы педагогов к студиям',
                'unique_together': {('teacher', 'studio')},
            },
        ),
    ]
