# Generated by Django 5.2.6 on 2026-04-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_child_first_name_child_last_name_child_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioenrollment',
            name='date_of_dismissal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отчисления'),
        ),
    ]
